# Generated by Django 2.2.1 on 2021-03-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='date published')),
                ('original_url', models.CharField(max_length=65)),
                ('shortened_url', models.CharField(max_length=65)),
                ('http_code', models.CharField(max_length=3)),
            ],
        ),
    ]
