# Generated by Django 2.2.1 on 2021-04-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorten', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='shortened_url',
            new_name='shortened_slug',
        ),
    ]
