# Generated by Django 2.2.1 on 2021-05-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorten', '0002_auto_20210408_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='http_code',
        ),
    ]
